version: 3.8build{build}
clone_depth: 5
branches:
  only:
    - master
    - /\d\.\d/
    - buildbot-custom
    - appveyor-cygwin
cache:
  - externals -> PCbuild
before_build:
  - ps: |+
      if ($env:APPVEYOR_RE_BUILD) {
        echo 'Doing full build due to re-build request.'
      } elseif (!$env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT) {
        echo 'Not a PR, doing full build.'
      } else {
        git fetch -q origin +refs/heads/$env:APPVEYOR_REPO_BRANCH
        $mergebase = git merge-base HEAD FETCH_HEAD
        $changes = git diff --name-only HEAD $mergebase | grep -vE '(\.rst$)|(^Doc)|(^Misc)'
        If (!$changes) {
          echo 'Only docs were updated, stopping build process.'
          Exit-AppveyorBuild
        } else {
          echo 'Doing full build due to non-doc changes in these files:'
          echo $changes
        }
      }


build_script:
- ps: |
    function Cygwin {
        $cygbin = "C:\\cygwin64\\bin"
        $project_path = & "$cygbin\\cygpath" -u -a $env:APPVEYOR_BUILD_FOLDER
        $cmd = ("C:\\cygwin64\\bin\\bash.exe -lc " +`
            "'cd $project_path; $($args -join " ")'")
        Invoke-Expression $cmd
        if ($LastExitCode -ne 0) {
            $host.SetShouldExit($LastExitCode)
        }
    }
    if ($env:PLATFORM -eq "Win32") {
        PCbuild\build.bat -e -p x64
        PCbuild\amd64\python.exe -m test.pythoninfo
    } elseif ($env:PLATFORM -eq "Cygwin64") {
        Cygwin cygcheck -s
        Cygwin curl -s --output apt-cyg https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg
        Cygwin chmod +x apt-cyg
        Cygwin ./apt-cyg install libcrypt-devel libffi-devel
        Cygwin ./configure
        Cygwin make -j4
        Cygwin ./python.exe -m test.pythoninfo
    }
test_script:
- ps: |
    if ($env:PLATFORM -eq "Win32") {
        PCbuild\rt.bat -x64 -q -uall -u-cpu -u-largefile -rwW --slowest --timeout=1200 --fail-env-changed -j0
    }
environment:
  HOST_PYTHON: C:\Python36\python.exe
image:
  - Visual Studio 2017
platform:
#    - Win32
    - Cygwin64
matrix:
    fast_finish: true
    allow_failures:
        - platform: Cygwin64
